### ISSUE TITLE
Crashes on a large solution

### ISSUE THREAD

**Issue by boskicthebrain** [feenkcom/roslyn2famix#1]
This is likely a bug in the roslyn-analyzer code. Stack trace:

> Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'FAMIX.ParameterizedType' to type 'FAMIX.Class'.
>    at ASTVisitor.VisitThrowStatement(ThrowStatementSyntax node)
>    at Microsoft.CodeAnalysis.CSharp.Syntax.ThrowStatementSyntax.Accept(CSharpSyntaxVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitBlock(BlockSyntax node)
>    at Microsoft.CodeAnalysis.CSharp.Syntax.BlockSyntax.Accept(CSharpSyntaxVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
>    at ASTVisitor.VisitMethodDeclaration(MethodDeclarationSyntax node)
>    at Microsoft.CodeAnalysis.CSharp.Syntax.MethodDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
>    at ASTVisitor.VisitClassDeclaration(ClassDeclarationSyntax node)
>    at Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitNamespaceDeclaration(NamespaceDeclarationSyntax node)
>    at Microsoft.CodeAnalysis.CSharp.Syntax.NamespaceDeclarationSyntax.Accept(CSharpSyntaxVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.DefaultVisit(SyntaxNode node)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxVisitor.VisitCompilationUnit(CompilationUnitSyntax node)
>    at Microsoft.CodeAnalysis.CSharp.Syntax.CompilationUnitSyntax.Accept(CSharpSyntaxVisitor visitor)
>    at Microsoft.CodeAnalysis.CSharp.CSharpSyntaxWalker.Visit(SyntaxNode node)
>    at RoslynMonoFamix.MainClass.Main(String[] args)

Unfortunately I don't have a minimal example where does it crash, as the tool doesn't give any info on what class did it fail.

**Comment by girba** [comment]
Thanks!

**Comment by georgeganea** [comment]
It should output the analysed file. I will try to reproduce based on the stacktrace though.

**Comment by boskicthebrain** [comment]
It didn't output anything :(

пон, 20. авг 2018. у 13:12 George Ganea <notifications@github.com> је
написао/ла:

**Comment by boskicthebrain** [comment]
You might also print the class name in the exception message. Then I could
try again and maybe be able to provide an minimal example.

пон, 20. авг 2018. у 15:06 Bosko Stupar <boskicthebrain@gmail.com> је
написао/ла:

**Comment by georgeganea** [comment]
This is how the output should look like 
<img width="1266" alt="screen shot 2018-08-24 at 13 41 31" src="https://user-images.githubusercontent.com/3874710/44580700-9ec4b700-a7a3-11e8-9fe0-236a6a5fc409.png">

**Comment by georgeganea** [comment]
The latest release should fix this issue. Please reopen it if this bug is still alive.
