### ISSUE TITLE
Moose can't import the created MSE-File

### ISSUE THREAD

**Issue by boskicthebrain** [feenkcom/roslyn2famix#2]
After generating an MSE-File from a very large C# Solution (3+ million code lines) I get endless Messages from Moose:
![image](https://user-images.githubusercontent.com/6009760/44918156-9687f100-ad3a-11e8-9076-79facacedf02.png)
I also reported it once via Report-button.

Please let me know how can I give you some more usable infos.

**Comment by georgeganea** [comment]
Hi, please make sure you have the latest moose installed. You can get it from https://dl.feenk.com/moose/moose32.zip. If it doesn't work with the latest version, I will take a look.

**Comment by boskicthebrain** [comment]
This was the latest Beta. Should I take the stable version?

пет, 31. авг 2018. у 16:38 George Ganea <notifications@github.com> је
написао/ла:

**Comment by georgeganea** [comment]
The image from the link I posted earlier should have the latest code. Please try it if possible.

**Comment by boskicthebrain** [comment]
I tried the latest image you posted and I get this:
![image](https://user-images.githubusercontent.com/6009760/45013939-2967aa80-b01d-11e8-8547-ac27c3368860.png)

**Comment by georgeganea** [comment]
I created a new release because the old one had a missing DLL which made the loaded projects not have standard libs resolved for them.
Unfortunately, that means having to reparse the entire solution. On top of that I did not actually manage to reproduce the exact issue, but it could be that the missing lib somehow messed up the extracted model.

**Comment by georgeganea** [comment]
Question: in your .mse file, do you have a FAMIX.Attribute with a "parentAnnotationType:"?

**Comment by boskicthebrain** [comment]
No parentAnnotationType but there is AnnotationType.
![image](https://user-images.githubusercontent.com/6009760/45027587-1adfba00-b042-11e8-9038-a47f93b71910.png)

**Comment by georgeganea** [comment]
There is now also a new moose release which addresses the issue you encountered. The link is the same as the one in one of the comments above.

**Comment by boskicthebrain** [comment]
It works! Thanks :) 🥇
